feat(action): adding multiple tf flavors for testing

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,21 +1,25 @@
-name: 'Tofu Action'
-description: 'Assists in running various tofu workflows from GitHub Actions.'
+name: 'TF Action'
+description: 'Assists in running various tf workflows from GitHub Actions.'
 inputs:
   # REQUIRED
+  tf_flavor:
+    description: 'Which flavor of tf infra-as-code to use; `tofu` or `terraform`'
+    type: string
+    required: true
   dir_path:
-    description: 'Path relative to root of repo for working tofu dir.'
+    description: 'Path relative to root of repo for working tf dir.'
     type: string
     required: true
   vars:
-    description: 'Path relative to working tofu dir for `.tfvars` file.'
+    description: 'Path relative to working tf dir for `.tfvars` file.'
     type: string
     required: true
   backend:
-    description: 'Path relative to working tofu dir for `.tfbackend` file.'
+    description: 'Path relative to working tf dir for `.tfbackend` file.'
     type: string
     required: true
   version:
-    description: 'Version of the tofu executable to install.'
+    description: 'Version of the tf executable to install.'
     type: string
     required: true
   # OPTIONAL
@@ -44,11 +48,15 @@ inputs:
     default: ''
 outputs:
   output:
-    description: 'Tofu outputs in -json format.'
+    description: 'tf outputs in -json format.'
     value: ${{ steps.apply.outputs.output }}
 runs:
   using: 'composite'
   steps:
+  - if: ${{ inputs.tf_flavor != 'tofu' && inputs.tf_flavor != 'terraform' }}
+    run: |
+      echo "::error file='jamcatbiz/do-tf/action.yml',line=56,endLine=56,title='Invalid Input tf_flavor'::'Valid values for tf_flavor include tofu and terraform."
+      exit 1
   - uses: actions/checkout@v4
   - uses: opentofu/setup-opentofu@v1
     with:
@@ -57,22 +65,22 @@ runs:
     if: ${{ inputs.plan_artifact_name != '' }}
     run: |
       cd ${{ inputs.dir_path }}
-      tofu fmt -check -recursive
-      tofu init -input=false \
+      ${{ inputs.tf_flavor }} fmt -check -recursive
+      ${{ inputs.tf_flavor }} init -input=false \
         -backend-config=${{ inputs.backend }} \
         ${{ inputs.init_args }}
-      tofu validate -no-color
-      tofu plan ${{ inputs.destroy && '-destroy' || '' }} \
+      ${{ inputs.tf_flavor }} validate -no-color
+      ${{ inputs.tf_flavor }} plan ${{ inputs.destroy && '-destroy' || '' }} \
         -no-color -input=false -out=tfplan \
         -var-file=${{ inputs.vars }} \
         ${{ inputs.plan_args }}
-      tofu show -no-color tfplan > tofu.txt
+      ${{ inputs.tf_flavor }} show -no-color tfplan > tf.txt
       {
-        echo "##### $(cat tofu.txt | grep --color=never -E '^[[:punct:]]|Plan')"
+        echo "##### $(cat tf.txt | grep --color=never -E '^[[:punct:]]|Plan')"
         echo "<details><summary>:mag: Show Plan</summary>"
         echo ""
         echo "\`\`\`hcl"
-        echo "$(cat tofu.txt)"
+        echo "$(cat tf.txt)"
         echo "\`\`\`"
         echo "</details>"
       } >> $GITHUB_STEP_SUMMARY
@@ -89,14 +97,14 @@ runs:
   - id: apply
     run: |
       cd ${{ inputs.dir_path }}
-      tofu apply -no-color -input=false ${{ inputs.plan_artifact_name != '' && inputs.plan_artifact_name || format('{0}-{1}-tfplan', inputs.dir_path, inputs.vars) }}
+      ${{ inputs.tf_flavor }} apply -no-color -input=false ${{ inputs.plan_artifact_name != '' && inputs.plan_artifact_name || format('{0}-{1}-tfplan', inputs.dir_path, inputs.vars) }}
       {
         echo 'output<<EOF'
-        echo $(tofu output -json)
+        echo $(${{ inputs.tf_flavor }} output -json)
         echo 'EOF'
       } >> $GITHUB_OUTPUT
       {
         echo "|Name|Value|"
         echo "|:-:|:-:|"
-        echo "$(tofu output -json | jq -r 'keys[] as $k | "|\`\($k)\`|\`\(.[$k].value)\`|"')"
+        echo "$(${{ inputs.tf_flavor }} output -json | jq -r 'keys[] as $k | "|\`\($k)\`|\`\(.[$k].value)\`|"')"
       } >> $GITHUB_STEP_SUMMARY
